<?php

return [
    'trabajadores' => [
        'title' => 'Listado de Trabajadores',
        'legacy_form' => 'frmRepTrabajadores',
        'legacy_report' => 'rptRepListadoDeTrabajadores',
        'procedure' => 'up_ReporteTrabajadores',
        'params' => [
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'estado' => ['label' => 'Estado', 'type' => 'select', 'default' => 'T', 'options' => ['T' => 'Todos', 'N' => 'Normal', 'S' => 'Suspendido']],
            'id_categoria' => ['label' => 'Categoria', 'type' => 'lookupselect', 'lookup' => 'categories', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'id_cargo' => ['label' => 'Cargo', 'type' => 'lookupselect', 'lookup' => 'positions', 'default' => 0],
            'id_area' => ['label' => 'Area', 'type' => 'lookupselect', 'lookup' => 'areas', 'default' => 0],
        ],
    ],
    'horarios' => [
        'title' => 'Listado de Horarios',
        'legacy_form' => 'frmRepListadoHorario',
        'legacy_report' => 'rptRepListadoDeHorario',
        'procedure' => 'up_ReporteHorariosTrab',
        'params' => [
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'id_cargo' => ['label' => 'Cargo', 'type' => 'lookupselect', 'lookup' => 'positions', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'datos-personal-privado' => [
        'title' => 'Datos Personal Privado',
        'legacy_form' => 'Planilla mensual web',
        'legacy_report' => 'Formato Excel/PDF mensual',
        'handler' => 'datosPersonalPrivado',
        'special_export' => 'private_monthly',
        'params' => [
            'ids_grupo' => ['label' => 'Grupos', 'type' => 'multiselect', 'lookup' => 'groups', 'default' => [], 'help' => 'Puede seleccionar uno o varios grupos.'],
            'solo_dia' => ['label' => 'Solo dia', 'type' => 'checkbox', 'default' => true],
            'id_cargo' => ['label' => 'Cargo', 'type' => 'lookupselect', 'lookup' => 'positions', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'registro-marcaciones' => [
        'title' => 'Registro de Marcaciones',
        'legacy_form' => 'FrmRepRegistroMarc',
        'legacy_report' => 'rptRepRegistroMarcacionFecha',
        'handler' => 'registroMarcaciones',
        'params' => [
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date', 'required' => true],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
            'hora_inicio' => ['label' => 'Hora inicio', 'type' => 'time', 'default' => '00:00'],
            'hora_fin' => ['label' => 'Hora fin', 'type' => 'time', 'default' => '23:59'],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_tipo_hora' => ['label' => 'Tipo hora', 'type' => 'lookupselect', 'lookup' => 'hour_types', 'default' => 0],
        ],
    ],
    'comparacion-horas' => [
        'title' => 'Comparacion de Horas Trabajadas',
        'legacy_form' => 'FrmRepComparacionHoras',
        'legacy_report' => 'rptRepComparacionHoraTrab',
        'handler' => 'comparacionHoras',
        'params' => [
            'tipo' => ['label' => 'Tipo', 'type' => 'select', 'default' => 'trabajadas', 'options' => [
                'trabajadas' => 'Horas trabajadas',
                'asistencia' => 'Asistencia',
                'listado' => 'Listado',
            ]],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date', 'required' => true],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date', 'required' => true],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
        ],
    ],
    'suspensiones' => [
        'title' => 'Listado de Suspensiones',
        'legacy_form' => 'frmRepListSusp',
        'legacy_report' => 'rptRepListadoDeSuspensiones',
        'procedure' => 'up_ReporteSuspensionesTrab',
        'params' => [
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'justificaciones' => [
        'title' => 'Listado de Justificaciones',
        'legacy_form' => 'FrmRepListJust',
        'legacy_report' => 'rptRepListadoDeJustificaciones',
        'handler' => 'justificaciones',
        'params' => [
            'formato' => ['label' => 'Formato', 'type' => 'select', 'default' => 'detalle', 'options' => ['detalle' => 'Detalle', 'listado' => 'Listado']],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'id_motivo' => ['label' => 'Motivo', 'type' => 'lookupselect', 'lookup' => 'reasons', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'no-marcaciones' => [
        'title' => 'Registro de No Marcaciones',
        'legacy_form' => 'FrmRepRegistroNoMarc',
        'legacy_report' => 'rptRepRegistroDeNoMarcacionesD',
        'handler' => 'noMarcaciones',
        'params' => [
            'tipo' => ['label' => 'Tipo', 'type' => 'select', 'default' => 'normal', 'options' => ['normal' => 'Normal', 'entrada_salida' => 'Entrada/Salida', 'ambas' => 'Ambas']],
            'formato' => ['label' => 'Formato', 'type' => 'select', 'default' => 'detalle', 'options' => ['detalle' => 'Detalle', 'listado' => 'Listado']],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'tardanzas' => [
        'title' => 'Record de Tardanzas',
        'legacy_form' => 'FrmRepRecordTard',
        'legacy_report' => 'rptRepRecordDeTardanzasD',
        'handler' => 'tardanzas',
        'params' => [
            'formato' => ['label' => 'Formato', 'type' => 'select', 'default' => 'detalle', 'options' => ['detalle' => 'Detalle', 'listado' => 'Listado']],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'inasistencias' => [
        'title' => 'Record de Inasistencias',
        'legacy_form' => 'FrmRepRecordInasist',
        'legacy_report' => 'rptRepRecordInasistenciasD',
        'handler' => 'inasistencias',
        'params' => [
            'formato' => ['label' => 'Formato', 'type' => 'select', 'default' => 'detalle', 'options' => ['detalle' => 'Detalle', 'listado' => 'Listado']],
            'solo_dia' => ['label' => 'Solo dia', 'type' => 'checkbox', 'default' => false],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'sobretiempos' => [
        'title' => 'Record de Sobretiempos',
        'legacy_form' => 'FrmRepRecordSobretiempo',
        'legacy_report' => 'rptRepRecordDeSobretiemposD',
        'handler' => 'sobretiempos',
        'params' => [
            'formato' => ['label' => 'Formato', 'type' => 'select', 'default' => 'detalle', 'options' => ['detalle' => 'Detalle', 'listado' => 'Listado']],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
            'id_grupo' => ['label' => 'Grupo', 'type' => 'lookupselect', 'lookup' => 'groups', 'default' => 0],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
    'detalle-asistencia' => [
        'title' => 'Detalle de Asistencia por Trabajador',
        'legacy_form' => 'FrmRepDetAsisTrab',
        'legacy_report' => 'rptRepDetalleAsistencia',
        'handler' => 'detalleAsistencia',
        'params' => [
            'formato' => ['label' => 'Formato', 'type' => 'select', 'default' => 'normal', 'options' => ['normal' => 'Normal', 'justificado' => 'Justificado', 'listado' => 'Listado']],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date', 'required' => true],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date', 'required' => true],
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'default' => 0],
        ],
    ],
    'consolidado-mensual' => [
        'title' => 'Consolidado Mensual',
        'legacy_form' => 'FrmRepConsolidado',
        'legacy_report' => 'rptRepConsolidadoMensual',
        'procedure' => 'up_ReporteConsolidados',
        'params' => [
            'mes' => ['label' => 'Mes', 'type' => 'number', 'default' => date('m')],
            'anio' => ['label' => 'Anio', 'type' => 'number', 'default' => date('Y')],
        ],
    ],
    'consolidado-trabajador' => [
        'title' => 'Consolidado por Trabajador',
        'legacy_form' => 'FrmRepConsolidadoxTrabajador',
        'legacy_report' => 'rptRepConsolidadoTrabajador',
        'handler' => 'consolidadoTrabajador',
        'params' => [
            'id_trabajador' => ['label' => 'Trabajador', 'type' => 'lookupselect', 'lookup' => 'employees', 'required' => true],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date', 'required' => true],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date', 'required' => true],
        ],
    ],
    'bitacora' => [
        'title' => 'Bitacora',
        'legacy_form' => 'FrmRepBitacora',
        'legacy_report' => 'rptRepBitacora',
        'handler' => 'bitacora',
        'params' => [
            'usuario' => ['label' => 'Usuario', 'type' => 'text'],
            'tabla' => ['label' => 'Tabla', 'type' => 'text'],
            'operacion' => ['label' => 'Operacion', 'type' => 'text'],
            'fecha_inicio' => ['label' => 'Fecha inicio', 'type' => 'date'],
            'fecha_fin' => ['label' => 'Fecha fin', 'type' => 'date'],
        ],
    ],
];
